# CI de Nivel 1 - Disparo manual a partir de 1 clique

# Nome da pipeline

name: 'Execucao Manual'

# Regras de disparo (gatilhos/triggers)
# gatilho de execl manual = workflow_dispatch

on:
  workflow_dispatch:


# trabalhos/tarefas dentro da pipeline = jobs
jobs:
  e2e-tests:

    # maquina que o job vai executar
    runs-on: ubuntu-latest

    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalacao do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      
      - uses: actions/upload-artifact@v2
      # instalacao do YARN
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalacao de dependencias
      - name: Instalando dependencias
        run: yarn

      # Instalando Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando Testes e2e
        run: yarn run e2e
      - name: Uploadar relatório de testes
        uses: actions/upload-artifact@v2
        with:
          name: relatorio-de-testes
          path: reports/coverage/lcov-report/src/**